### ISSUE TITLE
(maybe) re-add support for trailing slashes

### ISSUE THREAD

**Issue by sudo42** [RPGLibrarium/liberation#19]
Right now `/v1/titles` works, but `/v1/titles/` won't.  
Maybe we should support the "trailing slash" version, too ...

**Comment by Paradyx** [comment]
There is middleware for this feature in actix. I will add it in the full rewrite.

**Comment by sudo42** [comment]
Looking back at it … I don't think we need it — and am actually in favour of not doing it.
(I would consider trailing slashes to be kinda bad API design, for everything not explicitly being directory access/(sub-)resource listing.)
