### ISSUE TITLE
Keycloak version for docker-compose

### ISSUE THREAD

**Issue by sudo42** [RPGLibrarium/Liberation#5]
Initialization of Keycloak using `docker-compose up keycloak` fails due to database errors.
It seems to be related to the version of Keycloak: The problem persisted for multiple >=4.x versions, but vanished after using the tag `3.4.3.Final`.

We should either try to resolve the problems with the recent keycloak version (4.3.x), or enforce a working version (3.4.x) in the `docker-compose.yml`.

**Comment by sudo42** [comment]
@Paradyx can you check which version of keycloak you are running?

**Comment by Paradyx** [comment]
Just update Keycloak and everything seems to work fine

```
Server Version | 4.3.0.Final
-- | --
Server Profile | Community
Server Disabled Features | Account2, Docker
Server Time | Sat Aug 18 06:13:31 UTC 2018
Server Uptime | 0 days, 0 hours, 1 minute, 10 seconds
```

**Comment by sudo42** [comment]
Seemed to be an issue with newer versions of mariadb.
The file `docker-compose.yml` has already been updated.
Now it works _out of the box_.
