### ISSUE TITLE
Role-based access control with keycloak

### ISSUE THREAD

**Issue by Tikrass** [RPGLibrarium/liberation#8]
I suggest implementing fine grained roles for various actions in the Rest-API. The [Keycloak documentation](https://www.keycloak.org/docs/latest/server_admin/index.html#groups) explains how the concepts of roles, groups and users work together. For further reading I suggest the Wikipedia-article about [RBAC](https://en.wikipedia.org/wiki/Role-based_access_control) 

This would of course imply a documentation of the necessary roles linked to the API calls. 

### Pro's
- This would reuse already and well implemented features from Keycloak reducing complexity in the core server. 
- Flexibility and programmability for later extensions on a high non-code level.
- Standardized access control paradigm. 
- Access control is not hard-coded.
- New actions in the Rest-API can be added independently from the access control.
- No need for config files.

### Con's
- Maybe a little bit of work.

**Comment by Paradyx** [comment]
- I implemented a pre-validation of token with the actix-web `FromRequest` conversion which makes forgetting to validate the token harder. Any invalid token will be rejected. Missing token will return an well typed anonymous claim.
- I implemented new roles which represents the access to certain parts of the api. (`liberation:aristocrat`, `liberation:librarian:librarium`, `liberation:member`)
- Checking the claims is done trough a streamlined result handling

**Comment by Paradyx** [comment]
Actually I decided to go the really fine-grained approach now. 
```rust
    pub const ACCOUNTS_READ: &'static str = "liberation:accounts:read";
    pub const ACCOUNTS_EDIT: &'static str = "liberation:accounts:edit";
    pub const LIBRARIAN_ROLE_PREFIX: &'static str = "liberation:librarian:";
    pub const MEMBER_ROLE: &'static str = "liberation:member";
    pub const RPGSYSTEMS_EDIT: &'static str = "liberation:rpgsystems:edit";
    pub const RPGSYSTEMS_CREATE: &'static str = "liberation:rpgsystems:create";
    pub const RPGSYSTEMS_DELETE: &'static str = "liberation:rpgsystems:delete";
    pub const TITLES_EDIT: &'static str = "liberation:titles:edit";
    pub const TITLES_CREATE: &'static str = "liberation:titles:create";
    pub const TITLES_DELETE: &'static str = "liberation:titles:delete";
```
